service: notes-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/common/handler.index
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
